spring:
  application:
    name: llmentor-demo
  ai:
    dashscope:
      api-key: sk-8a0568dcae9a40bda1fb119e57002594
    chat:
      memory:
        repository: jdbc
  datasource:
    url: jdbc:mysql://rm-j6cqa79tge88ub053zo.mysql.rds.aliyuncs.com:3306/pndb_beta?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: pni18nbetadeveloper
    password: Oz1xas-B
    driver-class-name: com.mysql.cj.jdbc.Driver


server:
    port: 8000
