server:
  port: 8022
spring:
  application:
    name: LangChain4JRun
  ai:
    dashscope:
      api-key: sk-8a0568dcae9a40bda1fb119e57002594
langchain4j:
  open-ai:
    chat-model:
      api-key: sk-8a0568dcae9a40bda1fb119e57002594
      model-name: qwen-plus
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      log-requests: true
      log-responses: true
    streaming-chat-model:
      api-key: sk-8a0568dcae9a40bda1fb119e57002594
      model-name: qwen-plus
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      log-requests: true
      log-responses: true
